# frozen_string_literal: true

#
# Application Constants
#
module Constants
  #
  # Constants used during nations.xml parsing
  #
  module NationCollectors
    COLLECT_NOTHING ||= 1
    COLLECT_NAME ||= 2
    COLLECT_TYPE ||= 3
    COLLECT_FULLNAME ||= 4
    COLLECT_MOTTO ||= 5
    COLLECT_CATEGORY ||= 6
    COLLECT_UNSTATUS ||= 7
    COLLECT_ENDORSEMENTS ||= 8
    COLLECT_ISSUES_ANSWERED ||= 9
    COLLECT_CIVILRIGHTS ||= 10
    COLLECT_ECONOMY ||= 11
    COLLECT_POLITICALFREEDOM ||= 12
    COLLECT_REGION ||= 13
    COLLECT_POPULATION ||= 14
    COLLECT_TAX ||= 15
    COLLECT_ANIMAL ||= 16
    COLLECT_CURRENCY ||= 17
    COLLECT_DEMONYM ||= 18
    COLLECT_DEMONYM2 ||= 19
    COLLECT_DEMONYM2PLURAL ||= 20
    COLLECT_FLAG ||= 21
    COLLECT_MAJORINDUSTRY ||= 22
    COLLECT_GOVTPRIORITY ||= 23
    COLLECT_ADMINISTRATION ||= 24
    COLLECT_DEFENCE ||= 25
    COLLECT_EDUCATION ||= 26
    COLLECT_ENVIRONMENT ||= 27
    COLLECT_HEALTHCARE ||= 28
    COLLECT_COMMERCE ||= 29
    COLLECT_INTERNATIONALAID ||= 30
    COLLECT_LAWANDORDER ||= 31
    COLLECT_PUBLICTRANSPORT ||= 32
    COLLECT_SOCIALEQUALITY ||= 33
    COLLECT_SPIRITUALITY ||= 34
    COLLECT_WELFARE ||= 35
    COLLECT_FOUNDED ||= 36
    COLLECT_FIRSTLOGIN ||= 37
    COLLECT_LASTLOGIN ||= 38
    COLLECT_LASTACTIVITY ||= 39
    COLLECT_INFLUENCE ||= 40
    COLLECT_PUBLICSECTOR ||= 41
    COLLECT_CAUSE ||= 42
    COLLECT_LEADER ||= 43
    COLLECT_CAPITAL ||= 44
    COLLECT_RELIGION ||= 45
    COLLECT_FACTBOOKS ||= 46
    COLLECT_DISPATCHES ||= 47
    COLLECT_DBID ||= 48
  end

  #
  # Constants used during regions.xml parsing
  #
  module RegionCollectors
    COLLECT_NOTHING ||= 1
    COLLECT_NAME ||= 2
    COLLECT_FACTBOOK ||= 3
    COLLECT_NUMNATIONS ||= 4
    COLLECT_NATIONS ||= 5
    COLLECT_DELEGATE ||= 6
    COLLECT_DELEGATEVOTES ||= 7
    COLLECT_DELEGATEAUTH ||= 8
    COLLECT_FOUNDER ||= 9
    COLLECT_FOUNDERAUTH ||= 10
    COLLECT_OFFICER_NATION ||= 11
    COLLECT_OFFICER_OFFICE ||= 12
    COLLECT_OFFICER_AUTHORITY ||= 13
    COLLECT_OFFICER_TIME ||= 14
    COLLECT_OFFICER_BY ||= 15
    COLLECT_OFFICER_ORDER ||= 16
    COLLECT_POWER ||= 17
    COLLECT_FLAG ||= 18
    COLLECT_BANNER ||= 19
    COLLECT_EMBASSY ||= 20
    COLLECT_LASTUPDATE ||= 21
  end
end
